language: node_js
cache:
  yarn: true
node_js:
  - "4"
before_install:
  - cd site
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - time yarn
script:
  - time yarn run prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "tubealert.co.uk"
  skip_cleanup: true
  local_dir: public