language: node_js
cache:
  yarn: true
node_js:
  - "6"
before_script:
  - chmod +x script/deploy.sh
script:
  - yarn install
  - yarn test
  - yarn install --production --ignore-scripts --prefer-offline
  - ./script/deploy.sh
#deploy:
#  # Deploy the HTML (10 mins lifetime)
#  - provider: s3
#    region: $AWS_REGION
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: $AWS_BUCKET
#    skip_cleanup: true
#    acl: public_read
#    cache_control: "max-age=600"
#    local_dir: public/html
#  # Deploy the static assets (1 year lifetime)
#  - provider: s3
#    region: $AWS_REGION
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: $AWS_BUCKET
#    skip_cleanup: true
#    acl: public_read
#    cache_control: "max-age=31536000"
#    local_dir: public/static