language: node_js
cache:
  yarn: true
node_js:
  - "6"
before_script:
  - yarn global add serverless
script:
  - yarn install
  - yarn test
  - yarn install --production --ignore-scripts --prefer-offline
  - serverless deploy
deploy:
  # Deploy the static assets (1 year lifetime)
  - provider: s3
    region: $AWS_REGION
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $STATIC_BUCKET
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=31536000"
    local_dir: static
    on:
      branch: serverless
