language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - site/node_modules
node_js:
  - "4"
before_install:
  - cd site
  - time npm i -g yarn --cache-min 999999999
install:
  - time yarn
script:
  - time yarn run prod