language: node_js
cache:
  yarn: true
node_js:
  - "4"
before_install:
  - cd site
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - time yarn
script:
  - time yarn run prod